apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  labels:
    volume: my-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany 
  nfs:
    path: "/share"
    server: 10.173.231.34

