apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: frontend
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 1

