apiVersion: v1
kind: Pod
metadata:
  name: kuard
  # labels
  labels:
    app: web
  # annotations
  annotations:
    example.com/icon-url: "http://example.com/icon.png"
spec: 
  volumes:
    - name: "kuard-data"
      hostPath:
        path: "/var/lib/kuard"
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:3
    #- image: docker.io/tomcat
      name: kuard2
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      # volumes
      volumeMounts:
        - mountPath: "/data2"
          name: "kuard-data"
      # healthchecks - all
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      # healthchecks - redy/shutdown
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        periodSeconds: 2
        initialDelaySeconds: 0
        failureThreshold: 3
        successThreshold: 1
      # resources
      resources:
        requests:
          cpu: "250m"
          memory: "128Mi"
        limits:
          cpu: "300m"
          memory: "197Mi"

