apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: work-queue
  labels:
    app: work-queue
    component: queue
    chapter: jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      component: queue
    matchExpressions:
      - {key: component, operator: In, values: [queue]}
  template:
    metadata:
      # for select from service
      labels:
        app: work-queue
        component: queue
        chapter: jobs
    spec:
      containers:
      - name: queue
        image: "gcr.io/kuar-demo/kuard-amd64:1"
        imagePullPolicy: Always

