apiVersion: v1
kind: Service
metadata:
  labels:
    app: work-queue
    component: queue
    chapter: jobs
  name: queue
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  # selector service (replicaset-job-queue)
  selector:
    app: work-queue
    component: queue
    chapter: jobs

