apiVersion: v1
kind: Pod
metadata:
  name: kuard-mydisk-pod
spec:
  containers:
  - name: kuard-mydisk
    image: gcr.io/kuar-demo/kuard-amd64:3
    volumeMounts:
    - mountPath: "/mydisk-data"
      name: my-disk
  volumes:
  - name: my-disk
    persistentVolumeClaim:
      # DiskClaim to load
      claimName: mydisk
      readOnly: false

