apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver
  labels:
    volume: my-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany 
  nfs:
    path: "/share"
    server: 10.173.231.34

