apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:3.4.1
        # this container initializes the mongodb server, then sleeps.
        command:
        - mongod
        - --replSet
        - rs0
        ports:
        - containerPort: 27017
          name: web
        volumeMounts:
        - name: database
          mountPath: /data/db
        # health check
        livenessProbe:
          exec:
            command:
              - /usr/bin/mongo
              - --eval
              - db.serverStatus()
          timeoutSeconds: 10
          initialDelaySeconds: 10

      # init replicas
      - name: init-mongo
        image: mongo:3.4.1
        command:
        - bash
        - /config/init.sh
        volumeMounts:
        - name: config
          mountPath: /config
      # for test, is needed a vm 2vcpu or turnoff other containter
     #- name: kuard
     #  image: gcr.io/kuar-demo/kuard-amd64:3
     #  ports:
     #  - containerPort: 8080

      volumes:
      - name: config
        configMap:
          name: "mongo-init"

  volumeClaimTemplates:
  - metadata:
      name: database
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi


