apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: k8-app-py-hpa
  namespace: default
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: k8-app-py-deployment
  targetCPUUtilizationPercentage: 80
