apiVersion: v1
kind: Secret
metadata:
  name: k8-app-ssl-secrets
  namespace: default
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...

